Backend dev2
AlexBuchko/PolyFoodFinder pull request #77
Opened 2022-11-18 23:00 UTC by Ximixiyou

2022-11-29 00:59 UTC, Daniel-Redfern reviewed
I noticed some extra white space lines, are those prettier changes? Other than that everything looks good!

2022-11-29 01:01 UTC, jnlao requested changes

2022-11-29 01:01 UTC, jnlao commented on model/food-services.js
>      update: {field: value} can have 1+ field - value pairs
are these comments necessary? can we delete these?

2022-11-30 22:34 UTC, merged

2022-12-02 23:41 UTC, AlexBuchko commented
looks great to me!