Frontendstuff
AlexBuchko/PolyFoodFinder pull request #79
Opened 2022-11-29 00:48 UTC by Daniel-Redfern

Adds review display functionality.

2022-11-29 00:58 UTC, jnlao requested changes

2022-11-29 00:58 UTC, jnlao commented on frontend/src/index.css
> +
you can delete this extra blank line but everything else looks good!

2022-11-29 01:07 UTC, AlexBuchko requested changes

2022-11-29 01:07 UTC, AlexBuchko commented on frontend/src/Reviews.js
> +            event.preventDefault();
event.preventDefault() could be moved to the top of the function so it doesn't need to be stated in each branch

2022-11-29 01:07 UTC, AlexBuchko commented on frontend/src/Reviews.js
> +            <h3>Numerical Reviews</h3>
Could this be changed to "Ratings" instead of "Numerical Reviews"?

2022-11-29 01:43 UTC, AlexBuchko commented
Should probably fix whatever errors / warnings are causing the build to fail

2022-11-30 22:25 UTC, Ximixiyou reviewed
everything looks good, good job

2022-11-30 22:25 UTC, Ximixiyou commented on frontend/src/Reviews.js
> +        if((type === "likes" && lFlag === "True") || (type === "dislikes" && dFlag === "True") || (type === "poisonings" && pFlag === "True")){
this line is a bit confusing, could you leave a comment on it?

2022-11-30 23:04 UTC, merged